## This file is a template remove the .template to use the file

libraries:
  Movies:
    metadata_path:
    # - file: config/Movies.yml
    - pmm: genre
    - pmm: studio
    overlay_path:
    - remove_overlays: false
    - pmm: resolution
    - pmm: audio
    - pmm: ribbon
    - pmm: ratings
      template_variables:
        rating1: critic
        rating1_image: imdb

        rating2: audience
        rating2_image: rt_tomato

        rating3: user
        rating3_image: tmdb

        horizontal_position: right

    operations:
      mass_critic_rating_update: imdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_user_rating_update: tmdb
      split_duplicates: true

  TV Shows:
    metadata_path:
    # - file: config/TVShows.yml
    - pmm: streaming
    - pmm: network
    overlay_path:
    - remove_overlays: false
    - pmm: ribbon
    - pmm: ratings
      template_variables:
        rating1: critic
        rating1_image: imdb

        rating2: audience
        rating2_image: rt_popcorn

        rating3: user
        rating3_image: tmdb

        horizontal_position: right

    - pmm: ratings
      template_variables:
        overlay_level: episode
          
        rating1: critic
        rating1_image: imdb
          
        rating2: audience
        rating2_image: tmdb
        
        horizontal_position: right

    operations:
      mass_critic_rating_update: imdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_user_rating_update: tmdb
      mass_episode_critic_rating_update: imdb
      mass_episode_audience_rating_update: tmdb


settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_user:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
  show_unconfigured: true
  playlist_exclude_users:
webhooks:                        # Can be individually specified per library as well
  error:
  version:
  run_start:
  run_end:
  changes:
  delete:
plex:                            # Can be individually specified per library as well; REQUIRED for the script to run
  url: XXXXXXXXXXXXXXXXXXXXXX
  token: XXXXXXXXXXXXXXXXXXXXXX
  timeout: 60
  clean_bundles: 
  empty_trash: false
  optimize: false
omdb:
  apikey: ########
  cache_expiration: 60
mdblist:
  apikey: XXXXXXXXXXXXXXXXXXXXXX
  cache_expiration: 60
notifiarr:
  apikey: ####################################
anidb:                           # Not required for AniDB builders unless you want mature content
  username: ######
  password: ######
  language: en
  client:

Radarr:                          # Can be individually specified per library as well
  url: XXXXXXXXXXXXXXXXXXXXXX
  token: XXXXXXXXXXXXXXXXXXXXXX
  add_missing: false
  add_existing: false
  root_folder_path: /mnt/user/media/movies
  monitor: true
  availability: announcedTV-s
  quality_profile: HD-1080p
  tag:
  search: false
  radarr_path:
  plex_path:

Sonarr:                          # Can be individually specified per library as well
  url: XXXXXXXXXXXXXXXXXXXXXX
  token: XXXXXXXXXXXXXXXXXXXXXX
  add_missing: false
  add_existing: false
  root_folder_path: /mnt/user/media/tv series
  monitor: all
  quality_profile: HD-1080p
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:

trakt:
  client_id: 
  client_secret:
  pin:
  authorization:
    # everything below is autofilled by the script
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:

mal:
  client_id: ####################
  client_secret: ####################
  authorization:
    # everything below is autofilled by the script
    access_token:
    token_type:
    expires_in:
    refresh_token:

tmdb:
  apikey: XXXXXXXXXXXXXXXXXXXXXX
  language: en
  cache_expiration: 60
  region:
