{
 "title": "NUT UPS Dashboard",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "kwhprice", "label": "kWh Price", "query": "0.1974" },
   { "name": "upsdatasource", "label": "UPS Datasource", "query": "influxdb" },
   { "name": "Bucket", "query": "buckets()" },
   {
    "name": "Host",
    "label": "host",
    "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n\n  |> keyValues(keyColumns: [\"host\"])\n  |> group()\n  |> keep(columns: [\"host\"])\n  |> distinct(column: \"host\")\n"
   },
   {
    "name": "UPSmodel",
    "label": "model",
    "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  \n  |> keyValues(keyColumns: [\"model\"])\n  |> group()\n  |> keep(columns: [\"model\"])\n  |> distinct(column: \"model\")"
   },
   {
    "name": "Nominalpower",
    "label": "nominalpower",
    "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"nominal_power\")"
   }
  ]
 },
 "panels": [
  {
   "title": "UPS Load %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "alias": "UPS Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "ups.load" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 / 1000.0\n  }))\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Percent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"battery_charge_percent\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "battery.charge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_left_ns\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "battery.runtime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1h, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 / 1000.0\n  }))\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average UPS Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0\n  }))\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current UPS Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 \n  }))\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Today's Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1h, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * ${kwhprice} / 1000.0\n  }))\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180*$kwhprice" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load kWh",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Wh",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0\n  }))\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "This Week's Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * 24.0\n  }))\n  |> drop(columns: [\"host\"])\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "This Week Consumption/Costs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "kwatth", "label": "Load" }
   ],
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 25h, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * ${kwhprice} / 1000.0 * 24.0\n  }))\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180*$kwhprice" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 25h, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * 24.0 / 1000.0\n  }))\n  |> drop(columns: [\"host\"])\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "This Month Consumption/Costs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "kwatth", "label": "Load" }
   ],
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 7d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * ${kwhprice} / 1000.0 * 24.0\n  }))\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180*$kwhprice" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 7d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * 24.0 / 1000.0\n  }))\n  |> drop(columns: [\"host\"])\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "This Week's Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * ${kwhprice} / 1000.0 * 24.0\n  }))\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180*$kwhprice" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "This Month's Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * 24.0\n  }))\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "This Month's Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * ${kwhprice} / 1000.0 * 24.0\n  }))\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180*$kwhprice" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last 7 Day Power Consumption/Costs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "kwatth", "label": "Load" }
   ],
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 28h, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * ${kwhprice} / 1000.0 * 24.0\n  }))\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180*$kwhprice" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 28h, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * 24.0 / 1000.0\n  }))\n  |> drop(columns: [\"host\"])\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Month Power Consumption/Costs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 9, "y": 18 },
   "yaxes": [
    { "format": "kwatth", "label": "Load" }
   ],
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 7d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * ${kwhprice} / 1000.0 * 24.0\n  }))\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180*$kwhprice" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 7d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * 24.0 / 1000.0\n  }))\n  |> drop(columns: [\"host\"])\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "This Year's Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * 24.0 / 1000.0\n  }))\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "This Year's Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * ${kwhprice} / 1000.0 * 24.0\n  }))",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180*$kwhprice" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Estimated Yearly Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * 8765.999 / 1000.0\n  }))\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1000*24*365" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "This Years Consumption/Costs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "kwatth", "label": "Load" }
   ],
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 7d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * ${kwhprice} / 1000.0 * 24.0\n  }))",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180*$kwhprice" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 7d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * 24.0 / 1000.0\n  }))\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/180" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Estimated Yearly Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0 * ${kwhprice} / 1000.0 * 8765.999\n  }))",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1000*24*$kwhprice*365" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPS Load vs Time left",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 30 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "W",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ups_status",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"${Host}\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * ${Nominalpower}.0\n  }))\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "T",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ups_status",
     "query": "  from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_left_ns\")\n  |> filter(fn: (r) => r[\"model\"] == \"${UPSmodel}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n",
     "select": [
      [
       { "params": [ "battery.runtime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}