{
 "title": "pfSense System Dashboard",
 "tags": [
  "pfsense",
  "pfblocker",
  "telegraf"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "dataSource", "query": "influxdb" },
   {
    "name": "Host",
    "label": "pfSense",
    "query": "SHOW TAG VALUES FROM \"pf\" WITH KEY = \"host\""
   },
   {
    "name": "Disk",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"device\" WHERE \"host\" =~ /^$Host$/"
   },
   {
    "name": "Gateway",
    "query": "SHOW TAG VALUES FROM \"gateways\" WITH KEY = \"gateway_name\" WHERE \"host\" =~ /^$Host$/ "
   },
   { "name": "WAN", "query": "igb0,ovpnc1" },
   {
    "name": "LAN_Interfaces",
    "label": "LAN",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE \"host\" =~ /^$Host$/ "
   },
   {
    "name": "CPU",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\" WHERE \"host\" =~ /^$Host$/ and cpu !~ /cpu-total/"
   },
   {
    "name": "Sensor",
    "query": "SHOW TAG VALUES FROM \"temperature\" WITH KEY = \"sensor\" WHERE \"host\" =~ /^$Host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Hardware",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT \"n_users\" FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "n_users" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "CPU Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_cpu",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$CPU$/" }
     ]
    }
   ]
  },
  {
   "title": "Process Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "measurement": "processes",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Running" ], "type": "alias" }
      ],
      [
       { "params": [ "idle" ], "type": "field" }
      ],
      [
       { "params": [ "sleeping" ], "type": "field" }
      ],
      [
       { "params": [ "wait" ], "type": "field" }
      ],
      [
       { "params": [ "blocked" ], "type": "field" }
      ],
      [
       { "params": [ "zombies" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load1" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load5" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Load 15m",
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "PF Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "measurement": "pf",
     "select": [
      [
       { "params": [ "match" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Match" ], "type": "alias" }
      ],
      [
       { "params": [ "state-mismatch" ], "type": "field" },
       { "params": [ "State Mismatch" ], "type": "alias" }
      ],
      [
       { "params": [ "state-insert" ], "type": "field" },
       { "params": [ "State Insert" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_path",
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT \"used_percent\" FROM \"disk\" WHERE (\"host\" =~ /^$Host$/ AND \"path\" = '/var/run' AND \"device\" =~ /^$Disk$/) AND $timeFilter GROUP BY \"device\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "device", "operator": "!=", "value": "devfs" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$Disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Ram",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Ram Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SWAP Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "degrees" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$Sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "pfBlocker Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "IP - Top 10 Blocked - IN",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "$tag_src_ip",
     "groupBy": [
      { "params": [ "src_ip" ], "type": "tag" }
     ],
     "measurement": "tail_ipblock",
     "query": "SELECT TOP(\"count\",\"src_ip\",10) FROM (SELECT count(\"action\") FROM \"autogen\".\"tail_ip_block_log\" WHERE (\"host\" =~ /^$Host$/ AND \"action\" = 'block' AND \"direction\" = 'in') AND $timeFilter GROUP BY \"src_ip\") WHERE $timeFilter",
     "select": [
      [
       { "params": [ "action" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
     ]
    }
   ]
  },
  {
   "title": "IP - Top 10 Blocked - OUT",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 14 },
   "targets": [
    {
     "alias": "$tag_src_ip",
     "groupBy": [
      { "params": [ "src_ip" ], "type": "tag" }
     ],
     "measurement": "tail_ipblock",
     "query": "SELECT TOP(\"count\",\"src_ip\",10) FROM (SELECT count(\"action\") FROM \"autogen\".\"tail_ip_block_log\" WHERE (\"host\" =~ /^$Host$/ AND \"action\" = 'block' AND \"direction\" = 'out') AND $timeFilter GROUP BY \"src_ip\") WHERE $timeFilter",
     "select": [
      [
       { "params": [ "action" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
     ]
    }
   ]
  },
  {
   "title": "IP - Blocked Packet Stats",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail_ip_block_log",
     "select": [
      [
       { "params": [ "action" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Blocked Inbound" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "in" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "block" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail_ip_block_log",
     "select": [
      [
       { "params": [ "action" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Blocked Outbound" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "out" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "block" }
     ]
    }
   ]
  },
  {
   "title": "IP - Src/Dst Blocked Geo",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 14 },
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_geoip_code",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "geoip_code" ], "type": "tag" }
     ],
     "measurement": "tail_ip_block_log",
     "query": "SELECT count(\"action\") FROM \"ip_block_log\" WHERE $timeFilter GROUP BY \"GeoIP\"",
     "select": [
      [
       { "params": [ "action" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
     ]
    }
   ]
  },
  {
   "title": "DNSBL - Blocked Domain Queries",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail_dnsbl_log",
     "select": [
      [
       { "params": [ "duplicateeventstatus" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Blocked Domain Queries" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "DNSBL- Source IP - Top 10 Blocked",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 14 },
   "targets": [
    {
     "alias": "$tag_src_ip",
     "groupBy": [
      { "params": [ "tld" ], "type": "tag" }
     ],
     "measurement": "tail_dnsbl",
     "query": "SELECT TOP(\"count\",\"src_ip\",10) FROM (SELECT count(\"domain\") FROM \"autogen\".\"tail_dnsbl_log\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY \"src_ip\") WHERE $timeFilter",
     "select": [
      [
       { "params": [ "domain" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "DNSBL - Top 10 Blocked Domains",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 14 },
   "targets": [
    {
     "alias": "$tag_src_ip",
     "groupBy": [
      { "params": [ "tld" ], "type": "tag" }
     ],
     "measurement": "tail_dnsbl",
     "query": "SELECT TOP(\"count\",\"tld\",10) FROM (SELECT count(\"domain\") FROM \"autogen\".\"tail_dnsbl_log\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY \"tld\") WHERE $timeFilter",
     "select": [
      [
       { "params": [ "domain" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "pfBlocker Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "IP - Top 10 Blocked - IN (By Host/Port)",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "$tag_src_ip",
     "groupBy": [
      { "params": [ "src_ip" ], "type": "tag" }
     ],
     "measurement": "tail_ipblock",
     "query": "SELECT TOP(\"blocked\",10),src_ip,dest_ip, dest_port FROM\n(\nSELECT count(\"action\") as \"blocked\" FROM \"autogen\".\"tail_ip_block_log\" WHERE (\"host\" =~ /^$Host$/ AND \"action\" = 'block' AND \"direction\" = 'in' and protocolid =~ /^(6$|17$)/) AND $timeFilter GROUP BY src_ip,dest_ip,dest_port\n)  WHERE $timeFilter",
     "select": [
      [
       { "params": [ "action" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
     ]
    }
   ]
  },
  {
   "title": "Port - Top 10 Blocked - IN",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 24 },
   "targets": [
    {
     "alias": "$tag_src_ip",
     "groupBy": [
      { "params": [ "src_ip" ], "type": "tag" }
     ],
     "measurement": "tail_ipblock",
     "query": "SELECT TOP(\"blocked\",10),dest_port FROM\n(\nSELECT count(\"action\") as \"blocked\" FROM \"autogen\".\"tail_ip_block_log\" WHERE (\"host\" =~ /^$Host$/ AND \"action\" = 'block' AND \"direction\" = 'in' and protocolid =~ /^(6$|17$)/) AND $timeFilter GROUP BY dest_port\n)  WHERE $timeFilter",
     "select": [
      [
       { "params": [ "action" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
     ]
    }
   ]
  },
  {
   "title": "Top 10 DNSBL Feeds",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "feed_name" ], "type": "tag" }
     ],
     "measurement": "tail_dnsbl_log",
     "query": "SELECT count(*) FROM \"tail_dnsbl_log\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY \"feed_name\"",
     "select": [
      [
       { "params": [ "blockmethod" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Port - Top 10 Blocked - OUT",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 15, "y": 24 },
   "targets": [
    {
     "alias": "$tag_src_ip",
     "groupBy": [
      { "params": [ "src_ip" ], "type": "tag" }
     ],
     "measurement": "tail_ipblock",
     "query": "SELECT TOP(\"blocked\",10),dest_port FROM\n(\nSELECT count(\"action\") as \"blocked\" FROM \"autogen\".\"tail_ip_block_log\" WHERE (\"host\" =~ /^$Host$/ AND \"action\" = 'block' AND \"direction\" = 'out' and protocolid =~ /^(6$|17$)/) AND $timeFilter GROUP BY dest_port\n)  WHERE $timeFilter",
     "select": [
      [
       { "params": [ "action" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
     ]
    }
   ]
  },
  {
   "title": "IP - Top 10 Blocked - OUT (By Host/Port)",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 24 },
   "targets": [
    {
     "alias": "$tag_src_ip",
     "groupBy": [
      { "params": [ "src_ip" ], "type": "tag" }
     ],
     "measurement": "tail_ipblock",
     "query": "SELECT TOP(\"blocked\",10),src_ip,dest_ip, dest_port FROM\n(\nSELECT count(\"action\") as \"blocked\" FROM \"autogen\".\"tail_ip_block_log\" WHERE (\"host\" =~ /^$Host$/ AND \"action\" = 'block' AND \"direction\" = 'out' and protocolid =~ /^(6$|17$)/) AND $timeFilter GROUP BY src_ip,dest_ip,dest_port\n)  WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "action" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
     ]
    }
   ]
  },
  {
   "title": "IP - Top 10 Blocked - IN (By Host/Protocol)",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 33 },
   "targets": [
    {
     "alias": "$tag_src_ip",
     "groupBy": [
      { "params": [ "src_ip" ], "type": "tag" }
     ],
     "measurement": "tail_ipblock",
     "query": "SELECT TOP(\"blocked\",10),src_ip,dest_ip, protocol FROM\n(\nSELECT count(\"action\") as \"blocked\" FROM \"autogen\".\"tail_ip_block_log\" WHERE (\"host\" =~ /^$Host$/ AND \"action\" = 'block' AND \"direction\" = 'in' ) AND $timeFilter GROUP BY src_ip,dest_ip,protocol\n)  WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "action" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
     ]
    }
   ]
  },
  {
   "title": "Protocol - Top 10 Blocked - IN",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 33 },
   "targets": [
    {
     "alias": "$tag_protocol",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"action\") as \"blocked\" FROM \"autogen\".\"tail_ip_block_log\" WHERE (\"host\" =~ /^$Host$/ AND \"action\" = 'block' AND \"direction\" = 'in') AND $timeFilter GROUP BY protocol\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Protocol - Top 10 Blocked - OUT",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 15, "y": 33 },
   "targets": [
    {
     "alias": "$tag_protocol",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"action\") as \"blocked\" FROM \"autogen\".\"tail_ip_block_log\" WHERE (\"host\" =~ /^$Host$/ AND \"action\" = 'block' AND \"direction\" = 'out') AND $timeFilter GROUP BY protocol\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IP - Top 10 Blocked - OUT (By Host/Protocol)",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 33 },
   "targets": [
    {
     "alias": "$tag_src_ip",
     "groupBy": [
      { "params": [ "src_ip" ], "type": "tag" }
     ],
     "measurement": "tail_ipblock",
     "query": "SELECT TOP(\"blocked\",10),src_ip,dest_ip, protocol FROM\n(\nSELECT count(\"action\") as \"blocked\" FROM \"autogen\".\"tail_ip_block_log\" WHERE (\"host\" =~ /^$Host$/ AND \"action\" = 'block' AND \"direction\" = 'out' ) AND $timeFilter GROUP BY src_ip,dest_ip,protocol\n)  WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "action" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
     ]
    }
   ]
  },
  {
   "title": "Network Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Gateway RTT - $Gateway ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_gateway_name",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "gateway_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gateways",
     "select": [
      [
       { "params": [ "delay" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "gateway_name", "operator": "=~", "value": "/^$Gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 43 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "interface",
     "select": [
      [
       { "params": [ "friendlyname" ], "type": "field" },
       { "params": [ "FriendlyName" ], "type": "alias" }
      ],
      [
       { "params": [ "ip4_address" ], "type": "field" },
       { "params": [ "IPv4 Address" ], "type": "alias" }
      ],
      [
       { "params": [ "mac_address" ], "type": "field" },
       { "params": [ "Physical Address" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Status" ], "type": "alias" }
      ],
      [
       { "params": [ "ip6_address" ], "type": "field" },
       { "params": [ "IPv6 Address" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Gateway Loss - $Gateway ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_gateway_name",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "gateway_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gateways",
     "select": [
      [
       { "params": [ "loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "gateway_name", "operator": "=~", "value": "/^$Gateway$/" }
     ]
    }
   ]
  },
  {
   "title": "Gateway Summary - $Gateway",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 51 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "gateway_name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "gateways",
     "select": [
      [
       { "params": [ "gwdescr" ], "type": "field" }
      ],
      [
       { "params": [ "source" ], "type": "field" }
      ],
      [
       { "params": [ "monitor" ], "type": "field" }
      ],
      [
       { "params": [ "defaultgw" ], "type": "field" }
      ],
      [
       { "params": [ "status" ], "type": "field" }
      ],
      [
       { "params": [ "substatus" ], "type": "field" }
      ],
      [
       { "params": [ "interface" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Interface - $WAN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "repeat": "WAN",
   "targets": [
    {}
   ]
  },
  {
   "title": "Interface summary",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "interface",
     "select": [
      [
       { "params": [ "friendlyname" ], "type": "field" },
       { "params": [ "FriendlyName" ], "type": "alias" }
      ],
      [
       { "params": [ "ip4_address" ], "type": "field" },
       { "params": [ "IPv4 Address" ], "type": "alias" }
      ],
      [
       { "params": [ "mac_address" ], "type": "field" },
       { "params": [ "Physical Address" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$WAN$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Traffic - $WAN (Bytes/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_recv\") / count(\"bytes_recv\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_sent\") / count(\"bytes_sent\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$WAN$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Traffic - $WAN (Bits/sec)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_recv\") / count(\"bytes_recv\") * 8"
        ],
        "type": "math"
       },
       { "params": [ "Bits_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_sent\") / count(\"bytes_sent\") * 8"
        ],
        "type": "math"
       },
       { "params": [ "Bits_Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$WAN$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN $WAN",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col - This Month",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Bytes_Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$WAN$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN Throughput - $WAN",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"packets_recv\") / count(\"packets_recv\")"
        ],
        "type": "math"
       },
       { "params": [ "Packets_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "packets_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"packets_sent\") / count(\"packets_sent\")"
        ],
        "type": "math"
       },
       { "params": [ "Packets_Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Interface - $LAN_Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "repeat": "LAN_Interfaces",
   "targets": [
    {}
   ]
  },
  {
   "title": "Interface summary",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "interface",
     "select": [
      [
       { "params": [ "friendlyname" ], "type": "field" },
       { "params": [ "FriendlyName" ], "type": "alias" }
      ],
      [
       { "params": [ "ip4_address" ], "type": "field" },
       { "params": [ "IPv4 Address" ], "type": "alias" }
      ],
      [
       { "params": [ "mac_address" ], "type": "field" },
       { "params": [ "Physical Address" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Traffic - $LAN_Interfaces (Bytes/sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_recv\") / count(\"bytes_recv\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_sent\") / count(\"bytes_sent\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Traffic - $LAN_Interfaces (Bits/sec)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT derivative(mean(\"bytes_recv\"), 1s) *8 FROM \"net\" WHERE (\"host\" =~ /^$Host$/ AND \"interface\" =~ /^$LAN_Interfaces$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_recv\") / count(\"bytes_recv\") * 8"
        ],
        "type": "math"
       },
       { "params": [ "Bits_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_sent\") / count(\"bytes_sent\") * 8"
        ],
        "type": "math"
       },
       { "params": [ "Bits_Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN $LAN_Interfaces",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col - This Month",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Bytes_Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN Throughput - $LAN_Interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"packets_recv\") / count(\"packets_recv\")"
        ],
        "type": "math"
       },
       { "params": [ "Packets_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "packets_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"packets_sent\") / count(\"packets_sent\")"
        ],
        "type": "math"
       },
       { "params": [ "Packets_Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$LAN_Interfaces$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  }
 ]
}