{
 "title": "xeolab",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Power Consumption", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"2e21aa1143b8\")\n  |> filter(fn: (r) => r[\"model\"] == \"Back-UPS NS 1500M2\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * 900.0\n  }))\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"2e21aa1143b8\")\n  |> filter(fn: (r) => r[\"model\"] == \"Eaton 9PX 1500 RT\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * 1350.0\n  }))\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "APC Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"battery_charge_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"2e21aa1143b8\")\n  |> filter(fn: (r) => r[\"model\"] == \"Back-UPS NS 1500M2\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Today's Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "  from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"2e21aa1143b8\")\n  |> filter(fn: (r) => r[\"model\"] == \"Back-UPS NS 1500M2\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1h, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * 900.0 / 1000.0\n  }))\n  |> yield(name: \"last\")"
    },
    {
     "query": "  from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"2e21aa1143b8\")\n  |> filter(fn: (r) => r[\"model\"] == \"Eaton 9PX 1500 RT\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1h, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * 1350.0 / 1000.0\n  }))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "This Week's Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "  from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"5807f8eacc25\")\n  |> filter(fn: (r) => r[\"model\"] == \"Back-UPS NS 1500M2\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * 900.0 / 1000.0 * 24.0\n  }))\n  |> yield(name: \"last\")"
    },
    {
     "query": "  from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"5807f8eacc25\")\n  |> filter(fn: (r) => r[\"model\"] == \"Eaton 9PX 1500 RT\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * 1350.0 / 1000.0 * 24.0\n  }))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "This Month's Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "  from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"5807f8eacc25\")\n  |> filter(fn: (r) => r[\"model\"] == \"Back-UPS NS 1500M2\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * 900.0 / 1000.0 * 24.0\n  }))\n  |> yield(name: \"last\")"
    },
    {
     "query": "  from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"5807f8eacc25\")\n  |> filter(fn: (r) => r[\"model\"] == \"Eaton 9PX 1500 RT\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * 1350.0 / 1000.0 * 24.0\n  }))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "This Year's Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "  from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"5807f8eacc25\")\n  |> filter(fn: (r) => r[\"model\"] == \"Back-UPS NS 1500M2\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * 900.0  / 1000.0 * 24.0\n  }))\n  |> yield(name: \"last\")"
    },
    {
     "query": "  from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"5807f8eacc25\")\n  |> filter(fn: (r) => r[\"model\"] == \"Eaton 9PX 1500 RT\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * 1350.0  / 1000.0 * 24.0\n  }))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_left_ns\")\n  |> filter(fn: (r) => r[\"host\"] == \"2e21aa1143b8\")\n  |> filter(fn: (r) => r[\"model\"] == \"Back-UPS NS 1500M2\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_left_ns\")\n  |> filter(fn: (r) => r[\"host\"] == \"2e21aa1143b8\")\n  |> filter(fn: (r) => r[\"model\"] == \"Eaton 9PX 1500 RT\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "EATON Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"battery_charge_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"2e21aa1143b8\")\n  |> filter(fn: (r) => r[\"model\"] == \"Eaton 9PX 1500 RT\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Today's Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"2e21aa1143b8\")\n  |> filter(fn: (r) => r[\"model\"] == \"Back-UPS NS 1500M2\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1h, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * 900.0 * 0.1974 / 1000.0\n  }))\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"2e21aa1143b8\")\n  |> filter(fn: (r) => r[\"model\"] == \"Eaton 9PX 1500 RT\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1h, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * 1350.0 * 0.1974 / 1000.0\n  }))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "This Week's Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"5807f8eacc25\")\n  |> filter(fn: (r) => r[\"model\"] == \"Back-UPS NS 1500M2\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * 900.0 * 0.1974 / 1000.0 * 24.0\n  }))\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"5807f8eacc25\")\n  |> filter(fn: (r) => r[\"model\"] == \"Eaton 9PX 1500 RT\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * 1350.0 * 0.1974 / 1000.0 * 24.0\n  }))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "This Month's Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"5807f8eacc25\")\n  |> filter(fn: (r) => r[\"model\"] == \"Back-UPS NS 1500M2\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * 900.0 * 0.1974 / 1000.0 * 24.0\n  }))\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"5807f8eacc25\")\n  |> filter(fn: (r) => r[\"model\"] == \"Eaton 9PX 1500 RT\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * 1350.0 * 0.1974 / 1000.0 * 24.0\n  }))\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "This Year's Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"5807f8eacc25\")\n  |> filter(fn: (r) => r[\"model\"] == \"Back-UPS NS 1500M2\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * 900.0 * 0.1974 / 1000.0 * 24.0\n  }))\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"ups-nut\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"upsd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load_percent\")\n  |> filter(fn: (r) => r[\"host\"] == \"5807f8eacc25\")\n  |> filter(fn: (r) => r[\"model\"] == \"Eaton 9PX 1500 RT\")\n  |> filter(fn: (r) => r[\"status_OL\"] == \"true\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> map(fn: (r) => ({\n    r with\n    _value: float(v: r._value) / 100.0 * 1350.0 * 0.1974  / 1000.0 * 24.0\n  }))\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Temperature", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Ifa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "degrees" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "tz0" }
     ]
    }
   ]
  },
  {
   "title": "Moremi CPU 1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "cpu1-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-97XMBY1" }
     ]
    }
   ]
  },
  {
   "title": "Moremi CPU 2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "cpu2-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-97XMBY1" }
     ]
    }
   ]
  },
  {
   "title": "Shango CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "chip", "operator": "=", "value": "k10temp-pci-00c3" }
     ]
    }
   ]
  },
  {
   "title": "Moremi DRIVES S.M.A.R.T",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "smart_device",
     "select": [
      [
       { "params": [ "temp_c" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  },
  { "title": "CPU Load", "type": "text", "gridPos": { "h": 1, "w": 9, "x": 0, "y": 13 } },
  { "title": "Memory In Use", "type": "text", "gridPos": { "h": 1, "w": 9, "x": 9, "y": 13 } },
  {
   "title": "Ifa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"cpustat\" and\n    r._field == \"cpu\"\n  )\n  |> filter(fn: (r) => r[\"host\"] == \"moremi\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "ifa.local.xeolab.homes" }
     ]
    }
   ]
  },
  {
   "title": "Moremi",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"cpustat\" and\n    r._field == \"cpu\"\n  )\n  |> filter(fn: (r) => r[\"host\"] == \"moremi\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Shango",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Ifa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"memory\" and\n    r._field == \"memtotal\"\n  )\n  |> filter(fn: (r) => r[\"host\"] == \"moremi\")\n  |> limit(n:1)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ifa.local.xeolab.homes" }
     ]
    }
   ]
  },
  {
   "title": "Moremi",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"memory\" and\n    r._field == \"memused\"\n  )\n  |> filter(fn: (r) => r[\"host\"] == \"moremi\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({\n        r with\n        _value: float(v: r._value) / 1073741824.0\n      })\n    )\n  |> last()"
    }
   ]
  },
  {
   "title": "Shango",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"memory\" and\n    r._field == \"memtotal\"\n  )\n  |> filter(fn: (r) => r[\"host\"] == \"moremi\")\n  |> limit(n:1)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "shango" }
     ]
    }
   ]
  },
  { "title": "Network", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "IP - Src/Dst Blocked Geo",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 18 },
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_geoip_code",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "geoip_code" ], "type": "tag" }
     ],
     "measurement": "tail_ip_block_log",
     "query": "SELECT count(\"action\") FROM \"tail_ip_block_log\" WHERE (\"host\" =~ /^ifa\\.local\\.xeolab\\.homes$/ AND \"action\" = 'block' AND \"direction\" = 'in') AND time >= now() - 24h and time <= now() GROUP BY time(10m), \"geoip_code\"",
     "select": [
      [
       { "params": [ "action" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ifa.local.xeolab.homes" },
      { "condition": "AND", "key": "action", "operator": "=", "value": "block" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
     ]
    }
   ]
  },
  {
   "title": "WAN Traffic This Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Bytes_Send" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=", "value": "ifa.local.xeolab.homes" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "igb2" }
     ]
    }
   ]
  },
  {
   "title": "VPN Traffic This Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Bytes_Send" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=", "value": "ifa.local.xeolab.homes" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "tailscale0" }
     ]
    }
   ]
  },
  {
   "title": "IoT Traffic This Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Bytes_Send" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=", "value": "ifa.local.xeolab.homes" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "igb2.107" }
     ]
    }
   ]
  },
  {
   "title": "DataCenter Traffic This Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Bytes_Send" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=", "value": "ifa.local.xeolab.homes" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "igb2.30" }
     ]
    }
   ]
  },
  {
   "title": "Main Traffic This Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Bytes_Send" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=", "value": "ifa.local.xeolab.homes" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "igb2.40" }
     ]
    }
   ]
  },
  {
   "title": "Mgmt Traffic This Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Bytes_Send" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=", "value": "ifa.local.xeolab.homes" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "igb2.99" }
     ]
    }
   ]
  },
  { "title": "Storage Pool", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Shango",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system\")\n  |> filter(fn: (r) => r._field == \"avail\" or r._field == \"used\")\n  |> filter(fn: (r) => r[\"nodename\"] == \"moremi\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with \n    _time: r._time,\n    _measurement: r.measurement,\n    _field: \"used_perc\",\n    _value: float(v: 100) / (float(v: r.avail) + float(v: r.used)) * float(v:r.used)\n     }))\n  |> drop(columns: [\"avail\",\"used\"])\n",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       { "params": [ "Used %" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=~", "value": "/.*mnt/" },
      { "condition": "AND", "key": "fstype", "operator": "!~", "value": "/rootfs*/" }
     ]
    }
   ]
  },
  {
   "title": "Moremi",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system\")\n  |> filter(fn: (r) => r._field == \"avail\" or r._field == \"used\")\n  |> filter(fn: (r) => r[\"nodename\"] == \"moremi\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with \n    _time: r._time,\n    _measurement: r.measurement,\n    _field: \"used_perc\",\n    _value: float(v: 100) / (float(v: r.avail) + float(v: r.used)) * float(v:r.used)\n     }))\n  |> drop(columns: [\"avail\",\"used\"])\n"
    }
   ]
  },
  { "title": "Uptime", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 33 } },
  { "title": "Active Status", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 33 } },
  {
   "title": "Shango",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "shango" }
     ]
    }
   ]
  },
  {
   "title": "Moremi",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\n  |> filter(fn: (r) => r[\"host\"] == \"moremi\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "shango" }
     ]
    }
   ]
  },
  {
   "title": "TrueNAS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> filter(fn: (r) => r[\"host\"] == \"truenas-scale\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "system-globalstatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-97XMBY1" }
     ]
    }
   ]
  },
  {
   "title": "Ifa",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "gateways",
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> filter(fn: (r) => r[\"host\"] == \"tesla\")\n  |> filter(fn: (r) => r[\"host\"] == \"tesla\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ifa.local.xeolab.homes" },
      { "condition": "AND", "key": "gateway_name", "operator": "=", "value": "WAN_DHCP" }
     ]
    }
   ]
  },
  {
   "title": "TeslaMATE",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> filter(fn: (r) => r[\"host\"] == \"teslamate\")\n  |> filter(fn: (r) => r[\"object\"] == \"lxc\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "system-globalstatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-97XMBY1" }
     ]
    }
   ]
  },
  {
   "title": "Homebridge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> filter(fn: (r) => r[\"host\"] == \"homebridge\")\n  |> filter(fn: (r) => r[\"object\"] == \"lxc\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "system-globalstatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=", "value": "idrac-97XMBY1" }
     ]
    }
   ]
  },
  { "title": "Media ", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Streams",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "stream_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "Movies" }
     ]
    }
   ]
  },
  {
   "title": "Documentary Movies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "Documentary Movies" }
     ]
    }
   ]
  },
  {
   "title": "Top Users",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_friendly_name",
     "groupBy": [
      { "params": [ "friendly_name" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Location Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 39 },
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" },
      { "params": [ "full_location" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "TV Shows",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "TV Shows" }
     ]
    }
   ]
  },
  {
   "title": "Documentary Shows",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "Documentary Shows" }
     ]
    }
   ]
  },
  {
   "title": "AudioBooks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "section_name", "operator": "=", "value": "Audiobooks" }
     ]
    }
   ]
  },
  {
   "title": "Direct Plays",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "direct_play_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Direct Streams",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "direct_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Transcodes",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "transcode_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  }
 ]
}